cluster:
  name: argocd-project
  shortname: argocd-project
  dev_project_name: argocd-dev-apps
metadata:
  argocd_namespace: argocd
  helloworld_app_namespace: helloworld-app-ns

helloworld_app:
  label_from_cluster: clusterlabel
  replicas: 1
  resources:
    limits:
      cpu: '500m'
      memory: '256Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
