---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-nginxapp
  namespace: {{ .Values.metadata.argocd_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  destination:
    namespace: {{ .Values.metadata.nginx_app_namespace }}
    server: {{ .Values.cluster.url }}
  project: {{.Values.metadata.project}}
  source:
    path: resources/nginxapp
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    plugin: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
