---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helloworld
  namespace: {{ .Values.metadata.argocd_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  destination:
    namespace: {{ .Values.metadata.helloworld_app_namespace }}
    server: {{ .Values.cluster.url }}
  project: {{.Values.metadata.project}}
  source:
    plugin:
      name: argocd-vault-plugin-helm-custom        
      env:
      - name: HELM_VALUES
        value: --values values.yaml
      - name: HELM_ARGS
        value: >-
          --set helloworld_app.label_from_app={{.Values.helloworld_app.label_from_app}}
          --set helloworld_app.label_from_cluster ={{.Values.helloworld_app.label_from_cluster }}
    path: resources/helloworld
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
