---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helloworld
  namespace: {{ .Values.metadata.argocd_namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  destination:
    namespace: {{ .Values.metadata.helloworld_app_namespace }}
    server: {{ .Values.cluster.url }}
  project: {{.Values.metadata.project}}
  source:
    path: resources/helloworld
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
