apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: development
spec:
  generators:
  - git:
      files:
      - path: configurations/development/cluster-config.yaml
      repoURL: https://github.com/chandrapersi/argocd-repo
      revision: configuration
  template:
    metadata:
      name: {{cluster.dev_project_name}}
    spec:
      project: psl-argoproj-resources
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: apps
        repoURL: https://github.com/chandrapersi/argocd-repo
        targetRevision: code
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 2m
            factor: 3
            maxDuration: 8m
