apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: {{ .Values.metadata.helloworld_app_namespace }}
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081   
  type: NodePort
