repoURL: https://github.com/chandrapersi/argocd-repo
targetRevision: code
environment: dev
argocd_vault_plugin:
  name: argocd-vault-plugin-helm-custom
cluster:
  url: https://kubernetes.default.svc
metadata:
  project: psl-argoproj-resources
  argocd_namespace: argocd
  nginx_app_namespace: eks-sample-app
  helloworld_app_namespace: helloworld-app-ns
helloworld_app:
  label_from_app: applabel
